### PR TITLE
Add analysis worker

### PR DESCRIPTION
**Pull request by reisner**
Added functionality to the analyze button, and background worker for analysis tasks.

### CODE REVIEW

**Comment by ben-gready** [comment]
ok, I think I've found the issue -  `projectname` &  `quote` are defined in the `csvFileInput` module (in the UI function) and you're trying to access from the server function of the `AnalyzeNlp` module. We could either i) combine the modules (I don't recommend, since we could reuse the csv uploader in another app in the future), ii) call the two modules using the same namespace (id), so that they see a common set of variables, or iii) have the `AnalyzeNLP` module call the  `csvFile` module. 

iii) is probably the better option, whereas ii) would be more expedient

**Comment by ben-gready** [comment]
Hey @reisner I refactored a bit & I think made progress on your issue, but there is something weird that has cropped up in the display: `div form-group shiny-input-container` shows up above each UI element.  I'll try to get to the bottom of it tomorrow, but in the mean time, let me know what you think of the refactoring (feel free to take it or leave it)

**Comment by ben-gready** [comment]
I just added a fix for the `div form-group shiny-input-container` bug I mentioned above

**Comment by reisner** [comment]
@ben-gready ready for you to take a look please! It's a big one, so no rush!

**Comment by ben-gready** [comment]
working nicely on my machine...

**Pull request merged**
